basePath: /
host: localhost:6081
info:
  contact: {}
  description: API to simulate CPU and memory load
  title: GoPeck Stress Test API
  version: "1.0"
paths:
  /cpu:
    get:
      consumes:
      - application/json
      description: Perform CPU intensive calculation
      parameters:
      - default: 10000000
        description: Number of iterations
        in: query
        name: iterations
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: CPU Stress Test
      tags:
      - stress
  /memory:
    get:
      consumes:
      - application/json
      description: Allocate memory to simulate memory usage
      parameters:
      - default: 100
        description: Memory size in MB
        in: query
        name: sizeMB
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Memory Stress Test
      tags:
      - stress
  /ping:
    get:
      consumes:
      - application/json
      description: 用于测试服务是否可用
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping 接口
      tags:
      - Health
swagger: "2.0"
