// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitApp() (*gin.Engine, error) {
	config := NewConfig()
	db, err := NewDB(config)
	if err != nil {
		return nil, err
	}
	userRepository := NewUserRepository(db)
	userService := NewUserService(userRepository)
	userHandler := NewUserHandler(userService)
	engine := NewGinEngine(userHandler, config)
	return engine, nil
}

// wire.go:

func NewGinEngine(handler *UserHandler, cfg *Config) *gin.Engine {
	r := gin.Default()
	handler.RegisterRoutes(r)
	return r
}
